name: build and deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install Clasp
        run: yarn global add clasp
      - name: Create clasprc.json
        run: echo $'${{ secrets.CLASP_RC_JSON }}' > ~/.clasprc.json
      - name: Deploy
        run: clasp push
